image_proc:
  clr_detect:
    bgr_targ:
    - 41
    - 0
    - 169
    hue_tol: 10
    min_area: 40000
    sat:
      max: 255
      min: 30
    val:
      max: 255
      min: 30
  line_detect:
    canny:
      high: 150
      low: 100
    hough:
      thresh: 50
      max_gap: 50
      min_len: 50
    line:
      ang_excl: 30
      x_gap: 50
  crop:
    bottom: 1
    top: 0.5
  debug: true
  rescale: 2
webcam:
  cam_index: 0
  fps: 30
  size:
    height: 480
    width: 640
