{image_proc: {clr_detect: {bgr_targ: [119, 167, 182], hue_tol: 10, sat: {max: 255,
        min: 30}, val: {max: 255, min: 30}}, crop: {bottom: 1, top: 0.5}, debug: true,
    rescale: 2}, webcam: {cam_index: 0, fps: 30, size: {height: 480, width: 640}}}
